### ISSUE TITLE
ggfinallabel sometimes has an a in the legend.

### ISSUE THREAD

**Issue by melville1808** [MattCowgill/ggdirectlabel#9]
It's a relatively easy fix, although I don't really know if there are downstream consequences.

geom_finallabel <-
    function(mapping = NULL,
             data = NULL,
             stat = "identity",
             position = "identity",
             nudge_x = 0,
             nudge_y = 0,
             nudge_x_perc = 1.5,
             na.rm = FALSE,
             show.legend = NA,
             inherit.aes = TRUE,
             ...)

Change  show.legend = NA to show.legend = FALSE

**Comment by MattCowgill** [comment]
Thank you @melville1808 for opening this issue
